### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by AllanLRH** [daskeyboard/daskeyboard-applet--h2o-reminder-international#1] opened 2020-01-22 08:46 UTC
I get an error when I click _Install_ in the Q-software (launched without admin-rights, because I'm on a  my work computer).

Anyway to fix this, or for a starter, provide a better feedback?
![Capture](https://user-images.githubusercontent.com/2641327/72878860-0a45e780-3cfc-11ea-90ab-10d080e76674.PNG)

**Comment by fabiendv** [comment] 2021-04-07 13:41
This issue is not related to the applet.
It may happen when the connection is down. Can you try again?

I could not reproduce this behavior. Closing this issue.

Enjoy!

PS: next time, do not hesitate to contact [our support](https://daskeyboard.mojohelpdesk.com/login/create_request#/ticket-form-selection) for a quick assistance.

**Closed by fabiendv** 2021-04-07 13:41 UTC
